# .github/workflows/ci.yml
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Checks out your repository code
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Or your specific Node.js version
        cache: 'npm' # Caches node modules for faster builds
    - name: Install dependencies
      run: npm ci # Uses npm ci for clean installs in CI environments
    - name: Build Next.js app
      run: npm run build # Runs the build script defined in your package.json
    # You can add more steps here, e.g., for running tests:
    # - name: Run tests
    #   run: npm test